### ISSUE TITLE
Heroku Build Package

### ISSUE THREAD

**Issue by briviere** [Vifon/ledger-web#6]
Hello 

Would it be possible to make a Heroku Build Pack available?  I would like to have my own cloud based ledger-web.

thanks

Brian

**Comment by vifon** [comment]
I have only some basic experience with Heroku, so I'd need to read up on this topic. Sounds interesting but I cannot give you any timeline when to expect it.

If you want to make a Build Pack yourself, you're welcome to do so.

**Comment by briviere** [comment]
I see that there is a Heroku Branch.  Is that what's running on your demo site?  Would it be possible to provide the steps you used to get ledger-web running on Heroku?

thanks

Brian

**Comment by vifon** [comment]
Yes, that's the branch deployed on Heroku. Rebasing it onto the current `master` is probably a good idea.

These are the buildpacks I've got enabled:

- https://buildpack-registry.s3.amazonaws.com/buildpacks/heroku-community/apt.tgz
- heroku/python

You may need to enable PostgreSQL unless it gets added automatically. I don't remember the specific steps.

Apart from this and the `Procfile` that's already stored in Git I recall only one more custom step: you will need to log into the created instance to manually set the login credentials. Afterwards they will persist in the database. Speaking of which, watch out. While the DB provided by Heroku is persistent, the filesystem is not, and that's where the Ledger journal resides. To put it shortly, the Ledger data will be periodically wiped unless you'll find and apply some workaround. For a demo it's actually nice. For a personal instance not so much.

**Comment by vifon** [comment]
I presume this can be closed now that Heroku phased out their free tier?
