### ISSUE TITLE
ImportError: cannot import name 'AttestedCredentialData' from 'fido2.ctap2' 

### ISSUE THREAD

**Issue by jgera** [Vifon/ledger-web#8]
I am having an import error in the fresh install. This is my python env

cffi==1.15.1
cryptography==39.0.1
Django==2.2.28
fido2==1.1.0
numpy==1.24.2
pandas==1.5.3
pycparser==2.21
python-dateutil==2.8.2
pytz==2022.7.1
six==1.16.0
sqlparse==0.4.3

**Comment by vifon** [comment]
I should have known better than to leave this library version unpinned. :)

Thanks for reporting the problem. It should be fixed now but please verify.
